# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginregapp', '0003_auto_20180227_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_item', to='loginregapp.user'),
            preserve_default=False,
        ),
    ]
